version: '3.8'
services:
  llm:
    build: .
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - ../chatbox/backend/chat.db:/app/chat.db:ro
      - ./.env:/app/.env:ro
      - ./outputs:/app/plugin_outputs
    stdin_open: true
    tty: true
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
